<?php
/**
 * ProvidersApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * ProvidersApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProvidersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getAllProviders' => [
            'application/json',
        ],
        'getProvider' => [
            'application/json',
        ],
        'getProvidersCount' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAllProviders
     *
     * Get Providers
     *
     * @param  string|null $capability CHALLENGE_DEPOSIT_VERIFICATION - capability search is deprecated (optional)
     * @param  string|null $datasetfilter Expression to filter the providers by dataset(s) or dataset attribute(s). The default value will be the dataset or dataset attributes configured as default for the customer. (optional)
     * @param  string|null $full_account_number_fields Specify to filter the providers with values paymentAccountNumber,unmaskedAccountNumber. (optional)
     * @param  int|null $institution_id Institution Id for Single site selection (optional)
     * @param  string|null $name Name in minimum 1 character or routing number. (optional)
     * @param  string|null $priority Search priority (optional)
     * @param  string|null $provider_id Max 5 Comma seperated Provider Ids (optional)
     * @param  int|null $skip skip (Min 0) - This is not applicable along with &#39;name&#39; parameter. (optional)
     * @param  int|null $top top (Max 500) - This is not applicable along with &#39;name&#39; parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllProviders'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ProviderResponse|\OpenAPI\Client\Model\YodleeError
     */
    public function getAllProviders($capability = null, $datasetfilter = null, $full_account_number_fields = null, $institution_id = null, $name = null, $priority = null, $provider_id = null, $skip = null, $top = null, string $contentType = self::contentTypes['getAllProviders'][0])
    {
        list($response) = $this->getAllProvidersWithHttpInfo($capability, $datasetfilter, $full_account_number_fields, $institution_id, $name, $priority, $provider_id, $skip, $top, $contentType);
        return $response;
    }

    /**
     * Operation getAllProvidersWithHttpInfo
     *
     * Get Providers
     *
     * @param  string|null $capability CHALLENGE_DEPOSIT_VERIFICATION - capability search is deprecated (optional)
     * @param  string|null $datasetfilter Expression to filter the providers by dataset(s) or dataset attribute(s). The default value will be the dataset or dataset attributes configured as default for the customer. (optional)
     * @param  string|null $full_account_number_fields Specify to filter the providers with values paymentAccountNumber,unmaskedAccountNumber. (optional)
     * @param  int|null $institution_id Institution Id for Single site selection (optional)
     * @param  string|null $name Name in minimum 1 character or routing number. (optional)
     * @param  string|null $priority Search priority (optional)
     * @param  string|null $provider_id Max 5 Comma seperated Provider Ids (optional)
     * @param  int|null $skip skip (Min 0) - This is not applicable along with &#39;name&#39; parameter. (optional)
     * @param  int|null $top top (Max 500) - This is not applicable along with &#39;name&#39; parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllProviders'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ProviderResponse|\OpenAPI\Client\Model\YodleeError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllProvidersWithHttpInfo($capability = null, $datasetfilter = null, $full_account_number_fields = null, $institution_id = null, $name = null, $priority = null, $provider_id = null, $skip = null, $top = null, string $contentType = self::contentTypes['getAllProviders'][0])
    {
        $request = $this->getAllProvidersRequest($capability, $datasetfilter, $full_account_number_fields, $institution_id, $name, $priority, $provider_id, $skip, $top, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ProviderResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\YodleeError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ProviderResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ProviderResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\YodleeError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAllProvidersAsync
     *
     * Get Providers
     *
     * @param  string|null $capability CHALLENGE_DEPOSIT_VERIFICATION - capability search is deprecated (optional)
     * @param  string|null $datasetfilter Expression to filter the providers by dataset(s) or dataset attribute(s). The default value will be the dataset or dataset attributes configured as default for the customer. (optional)
     * @param  string|null $full_account_number_fields Specify to filter the providers with values paymentAccountNumber,unmaskedAccountNumber. (optional)
     * @param  int|null $institution_id Institution Id for Single site selection (optional)
     * @param  string|null $name Name in minimum 1 character or routing number. (optional)
     * @param  string|null $priority Search priority (optional)
     * @param  string|null $provider_id Max 5 Comma seperated Provider Ids (optional)
     * @param  int|null $skip skip (Min 0) - This is not applicable along with &#39;name&#39; parameter. (optional)
     * @param  int|null $top top (Max 500) - This is not applicable along with &#39;name&#39; parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllProviders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllProvidersAsync($capability = null, $datasetfilter = null, $full_account_number_fields = null, $institution_id = null, $name = null, $priority = null, $provider_id = null, $skip = null, $top = null, string $contentType = self::contentTypes['getAllProviders'][0])
    {
        return $this->getAllProvidersAsyncWithHttpInfo($capability, $datasetfilter, $full_account_number_fields, $institution_id, $name, $priority, $provider_id, $skip, $top, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllProvidersAsyncWithHttpInfo
     *
     * Get Providers
     *
     * @param  string|null $capability CHALLENGE_DEPOSIT_VERIFICATION - capability search is deprecated (optional)
     * @param  string|null $datasetfilter Expression to filter the providers by dataset(s) or dataset attribute(s). The default value will be the dataset or dataset attributes configured as default for the customer. (optional)
     * @param  string|null $full_account_number_fields Specify to filter the providers with values paymentAccountNumber,unmaskedAccountNumber. (optional)
     * @param  int|null $institution_id Institution Id for Single site selection (optional)
     * @param  string|null $name Name in minimum 1 character or routing number. (optional)
     * @param  string|null $priority Search priority (optional)
     * @param  string|null $provider_id Max 5 Comma seperated Provider Ids (optional)
     * @param  int|null $skip skip (Min 0) - This is not applicable along with &#39;name&#39; parameter. (optional)
     * @param  int|null $top top (Max 500) - This is not applicable along with &#39;name&#39; parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllProviders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllProvidersAsyncWithHttpInfo($capability = null, $datasetfilter = null, $full_account_number_fields = null, $institution_id = null, $name = null, $priority = null, $provider_id = null, $skip = null, $top = null, string $contentType = self::contentTypes['getAllProviders'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ProviderResponse';
        $request = $this->getAllProvidersRequest($capability, $datasetfilter, $full_account_number_fields, $institution_id, $name, $priority, $provider_id, $skip, $top, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllProviders'
     *
     * @param  string|null $capability CHALLENGE_DEPOSIT_VERIFICATION - capability search is deprecated (optional)
     * @param  string|null $datasetfilter Expression to filter the providers by dataset(s) or dataset attribute(s). The default value will be the dataset or dataset attributes configured as default for the customer. (optional)
     * @param  string|null $full_account_number_fields Specify to filter the providers with values paymentAccountNumber,unmaskedAccountNumber. (optional)
     * @param  int|null $institution_id Institution Id for Single site selection (optional)
     * @param  string|null $name Name in minimum 1 character or routing number. (optional)
     * @param  string|null $priority Search priority (optional)
     * @param  string|null $provider_id Max 5 Comma seperated Provider Ids (optional)
     * @param  int|null $skip skip (Min 0) - This is not applicable along with &#39;name&#39; parameter. (optional)
     * @param  int|null $top top (Max 500) - This is not applicable along with &#39;name&#39; parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllProviders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllProvidersRequest($capability = null, $datasetfilter = null, $full_account_number_fields = null, $institution_id = null, $name = null, $priority = null, $provider_id = null, $skip = null, $top = null, string $contentType = self::contentTypes['getAllProviders'][0])
    {











        $resourcePath = '/providers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $capability,
            'capability', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $datasetfilter,
            'dataset$filter', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $full_account_number_fields,
            'fullAccountNumberFields', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $institution_id,
            'institutionId', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $name,
            'name', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $priority,
            'priority', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $provider_id,
            'providerId', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skip,
            'skip', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $top,
            'top', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json;charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getProvider
     *
     * Get Provider Details
     *
     * @param  int $provider_id providerId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProvider'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ProviderDetailResponse|\OpenAPI\Client\Model\YodleeError
     */
    public function getProvider($provider_id, string $contentType = self::contentTypes['getProvider'][0])
    {
        list($response) = $this->getProviderWithHttpInfo($provider_id, $contentType);
        return $response;
    }

    /**
     * Operation getProviderWithHttpInfo
     *
     * Get Provider Details
     *
     * @param  int $provider_id providerId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProvider'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ProviderDetailResponse|\OpenAPI\Client\Model\YodleeError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProviderWithHttpInfo($provider_id, string $contentType = self::contentTypes['getProvider'][0])
    {
        $request = $this->getProviderRequest($provider_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ProviderDetailResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\YodleeError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ProviderDetailResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ProviderDetailResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\YodleeError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getProviderAsync
     *
     * Get Provider Details
     *
     * @param  int $provider_id providerId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProvider'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProviderAsync($provider_id, string $contentType = self::contentTypes['getProvider'][0])
    {
        return $this->getProviderAsyncWithHttpInfo($provider_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProviderAsyncWithHttpInfo
     *
     * Get Provider Details
     *
     * @param  int $provider_id providerId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProvider'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProviderAsyncWithHttpInfo($provider_id, string $contentType = self::contentTypes['getProvider'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ProviderDetailResponse';
        $request = $this->getProviderRequest($provider_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProvider'
     *
     * @param  int $provider_id providerId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProvider'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getProviderRequest($provider_id, string $contentType = self::contentTypes['getProvider'][0])
    {

        // verify the required parameter 'provider_id' is set
        if ($provider_id === null || (is_array($provider_id) && count($provider_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $provider_id when calling getProvider'
            );
        }


        $resourcePath = '/providers/{providerId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($provider_id !== null) {
            $resourcePath = str_replace(
                '{' . 'providerId' . '}',
                ObjectSerializer::toPathValue($provider_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json;charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getProvidersCount
     *
     * Get Providers Count
     *
     * @param  string|null $capability CHALLENGE_DEPOSIT_VERIFICATION - capability search is deprecated (optional)
     * @param  string|null $datasetfilter Expression to filter the providers by dataset(s) or dataset attribute(s). The default value will be the dataset or dataset attributes configured as default for the customer. (optional)
     * @param  string|null $full_account_number_fields Specify to filter the providers with values paymentAccountNumber,unmaskedAccountNumber. (optional)
     * @param  string|null $name Name in minimum 1 character or routing number. (optional)
     * @param  string|null $priority Search priority (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProvidersCount'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ProvidersCountResponse|\OpenAPI\Client\Model\YodleeError
     */
    public function getProvidersCount($capability = null, $datasetfilter = null, $full_account_number_fields = null, $name = null, $priority = null, string $contentType = self::contentTypes['getProvidersCount'][0])
    {
        list($response) = $this->getProvidersCountWithHttpInfo($capability, $datasetfilter, $full_account_number_fields, $name, $priority, $contentType);
        return $response;
    }

    /**
     * Operation getProvidersCountWithHttpInfo
     *
     * Get Providers Count
     *
     * @param  string|null $capability CHALLENGE_DEPOSIT_VERIFICATION - capability search is deprecated (optional)
     * @param  string|null $datasetfilter Expression to filter the providers by dataset(s) or dataset attribute(s). The default value will be the dataset or dataset attributes configured as default for the customer. (optional)
     * @param  string|null $full_account_number_fields Specify to filter the providers with values paymentAccountNumber,unmaskedAccountNumber. (optional)
     * @param  string|null $name Name in minimum 1 character or routing number. (optional)
     * @param  string|null $priority Search priority (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProvidersCount'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ProvidersCountResponse|\OpenAPI\Client\Model\YodleeError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProvidersCountWithHttpInfo($capability = null, $datasetfilter = null, $full_account_number_fields = null, $name = null, $priority = null, string $contentType = self::contentTypes['getProvidersCount'][0])
    {
        $request = $this->getProvidersCountRequest($capability, $datasetfilter, $full_account_number_fields, $name, $priority, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ProvidersCountResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\YodleeError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ProvidersCountResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ProvidersCountResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\YodleeError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getProvidersCountAsync
     *
     * Get Providers Count
     *
     * @param  string|null $capability CHALLENGE_DEPOSIT_VERIFICATION - capability search is deprecated (optional)
     * @param  string|null $datasetfilter Expression to filter the providers by dataset(s) or dataset attribute(s). The default value will be the dataset or dataset attributes configured as default for the customer. (optional)
     * @param  string|null $full_account_number_fields Specify to filter the providers with values paymentAccountNumber,unmaskedAccountNumber. (optional)
     * @param  string|null $name Name in minimum 1 character or routing number. (optional)
     * @param  string|null $priority Search priority (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProvidersCount'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProvidersCountAsync($capability = null, $datasetfilter = null, $full_account_number_fields = null, $name = null, $priority = null, string $contentType = self::contentTypes['getProvidersCount'][0])
    {
        return $this->getProvidersCountAsyncWithHttpInfo($capability, $datasetfilter, $full_account_number_fields, $name, $priority, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProvidersCountAsyncWithHttpInfo
     *
     * Get Providers Count
     *
     * @param  string|null $capability CHALLENGE_DEPOSIT_VERIFICATION - capability search is deprecated (optional)
     * @param  string|null $datasetfilter Expression to filter the providers by dataset(s) or dataset attribute(s). The default value will be the dataset or dataset attributes configured as default for the customer. (optional)
     * @param  string|null $full_account_number_fields Specify to filter the providers with values paymentAccountNumber,unmaskedAccountNumber. (optional)
     * @param  string|null $name Name in minimum 1 character or routing number. (optional)
     * @param  string|null $priority Search priority (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProvidersCount'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProvidersCountAsyncWithHttpInfo($capability = null, $datasetfilter = null, $full_account_number_fields = null, $name = null, $priority = null, string $contentType = self::contentTypes['getProvidersCount'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ProvidersCountResponse';
        $request = $this->getProvidersCountRequest($capability, $datasetfilter, $full_account_number_fields, $name, $priority, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProvidersCount'
     *
     * @param  string|null $capability CHALLENGE_DEPOSIT_VERIFICATION - capability search is deprecated (optional)
     * @param  string|null $datasetfilter Expression to filter the providers by dataset(s) or dataset attribute(s). The default value will be the dataset or dataset attributes configured as default for the customer. (optional)
     * @param  string|null $full_account_number_fields Specify to filter the providers with values paymentAccountNumber,unmaskedAccountNumber. (optional)
     * @param  string|null $name Name in minimum 1 character or routing number. (optional)
     * @param  string|null $priority Search priority (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProvidersCount'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getProvidersCountRequest($capability = null, $datasetfilter = null, $full_account_number_fields = null, $name = null, $priority = null, string $contentType = self::contentTypes['getProvidersCount'][0])
    {







        $resourcePath = '/providers/count';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $capability,
            'capability', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $datasetfilter,
            'dataset$filter', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $full_account_number_fields,
            'fullAccountNumberFields', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $name,
            'name', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $priority,
            'priority', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json;charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
