<?php
/**
 * DerivedTransactionsSummary
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RewardsWise\Yodlee\OpenAPI\Client\Model;

use \ArrayAccess;
use \RewardsWise\Yodlee\OpenAPI\Client\ObjectSerializer;

/**
 * DerivedTransactionsSummary Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DerivedTransactionsSummary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DerivedTransactionsSummary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'category_type' => 'string',
        'category_summary' => '\RewardsWise\Yodlee\OpenAPI\Client\Model\DerivedCategorySummary[]',
        'credit_total' => '\RewardsWise\Yodlee\OpenAPI\Client\Model\Money',
        'links' => '\RewardsWise\Yodlee\OpenAPI\Client\Model\DerivedTransactionsLinks',
        'debit_total' => '\RewardsWise\Yodlee\OpenAPI\Client\Model\Money'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'category_type' => null,
        'category_summary' => null,
        'credit_total' => null,
        'links' => null,
        'debit_total' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'category_type' => false,
        'category_summary' => false,
        'credit_total' => false,
        'links' => false,
        'debit_total' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'category_type' => 'categoryType',
        'category_summary' => 'categorySummary',
        'credit_total' => 'creditTotal',
        'links' => 'links',
        'debit_total' => 'debitTotal'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'category_type' => 'setCategoryType',
        'category_summary' => 'setCategorySummary',
        'credit_total' => 'setCreditTotal',
        'links' => 'setLinks',
        'debit_total' => 'setDebitTotal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'category_type' => 'getCategoryType',
        'category_summary' => 'getCategorySummary',
        'credit_total' => 'getCreditTotal',
        'links' => 'getLinks',
        'debit_total' => 'getDebitTotal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CATEGORY_TYPE_TRANSFER = 'TRANSFER';
    public const CATEGORY_TYPE_DEFERRED_COMPENSATION = 'DEFERRED_COMPENSATION';
    public const CATEGORY_TYPE_UNCATEGORIZE = 'UNCATEGORIZE';
    public const CATEGORY_TYPE_INCOME = 'INCOME';
    public const CATEGORY_TYPE_EXPENSE = 'EXPENSE';
    public const CATEGORY_TYPE_LOAN = 'LOAN';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCategoryTypeAllowableValues()
    {
        return [
            self::CATEGORY_TYPE_TRANSFER,
            self::CATEGORY_TYPE_DEFERRED_COMPENSATION,
            self::CATEGORY_TYPE_UNCATEGORIZE,
            self::CATEGORY_TYPE_INCOME,
            self::CATEGORY_TYPE_EXPENSE,
            self::CATEGORY_TYPE_LOAN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('category_type', $data ?? [], null);
        $this->setIfExists('category_summary', $data ?? [], null);
        $this->setIfExists('credit_total', $data ?? [], null);
        $this->setIfExists('links', $data ?? [], null);
        $this->setIfExists('debit_total', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCategoryTypeAllowableValues();
        if (!is_null($this->container['category_type']) && !in_array($this->container['category_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'category_type', must be one of '%s'",
                $this->container['category_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets category_type
     *
     * @return string|null
     */
    public function getCategoryType()
    {
        return $this->container['category_type'];
    }

    /**
     * Sets category_type
     *
     * @param string|null $category_type Type of categories provided by transactions/categories service.<br><br><b>Applicable containers</b>: creditCard, bank, investment<br><b>Applicable Values</b><br>
     *
     * @return self
     */
    public function setCategoryType($category_type)
    {
        if (is_null($category_type)) {
            throw new \InvalidArgumentException('non-nullable category_type cannot be null');
        }
        $allowedValues = $this->getCategoryTypeAllowableValues();
        if (!in_array($category_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'category_type', must be one of '%s'",
                    $category_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['category_type'] = $category_type;

        return $this;
    }

    /**
     * Gets category_summary
     *
     * @return \RewardsWise\Yodlee\OpenAPI\Client\Model\DerivedCategorySummary[]|null
     */
    public function getCategorySummary()
    {
        return $this->container['category_summary'];
    }

    /**
     * Sets category_summary
     *
     * @param \RewardsWise\Yodlee\OpenAPI\Client\Model\DerivedCategorySummary[]|null $category_summary Summary of transaction amouts at category level.<br><br><b>Applicable containers</b>: creditCard, bank, investment<br>
     *
     * @return self
     */
    public function setCategorySummary($category_summary)
    {
        if (is_null($category_summary)) {
            throw new \InvalidArgumentException('non-nullable category_summary cannot be null');
        }
        $this->container['category_summary'] = $category_summary;

        return $this;
    }

    /**
     * Gets credit_total
     *
     * @return \RewardsWise\Yodlee\OpenAPI\Client\Model\Money|null
     */
    public function getCreditTotal()
    {
        return $this->container['credit_total'];
    }

    /**
     * Sets credit_total
     *
     * @param \RewardsWise\Yodlee\OpenAPI\Client\Model\Money|null $credit_total credit_total
     *
     * @return self
     */
    public function setCreditTotal($credit_total)
    {
        if (is_null($credit_total)) {
            throw new \InvalidArgumentException('non-nullable credit_total cannot be null');
        }
        $this->container['credit_total'] = $credit_total;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \RewardsWise\Yodlee\OpenAPI\Client\Model\DerivedTransactionsLinks|null
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \RewardsWise\Yodlee\OpenAPI\Client\Model\DerivedTransactionsLinks|null $links links
     *
     * @return self
     */
    public function setLinks($links)
    {
        if (is_null($links)) {
            throw new \InvalidArgumentException('non-nullable links cannot be null');
        }
        $this->container['links'] = $links;

        return $this;
    }

    /**
     * Gets debit_total
     *
     * @return \RewardsWise\Yodlee\OpenAPI\Client\Model\Money|null
     */
    public function getDebitTotal()
    {
        return $this->container['debit_total'];
    }

    /**
     * Sets debit_total
     *
     * @param \RewardsWise\Yodlee\OpenAPI\Client\Model\Money|null $debit_total debit_total
     *
     * @return self
     */
    public function setDebitTotal($debit_total)
    {
        if (is_null($debit_total)) {
            throw new \InvalidArgumentException('non-nullable debit_total cannot be null');
        }
        $this->container['debit_total'] = $debit_total;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


